
services:
  backend:
    build: .
    container_name: backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RIOT_TOKEN=${RIOT_TOKEN}
      - NODE_ENV=${NODE_ENV}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lowheel.rule=Host(`lowheel.duckdns.org`)"
      - "traefik.http.routers.lowheel.entrypoints=websecure"
      - "traefik.http.routers.lowheel.tls=true" 
      - "traefik.http.routers.lowheel.tls.certresolver=letsencrypt"
      - "traefik.http.services.lowheel.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy-public"
    restart: always
    networks:
      - proxy-public

networks:
  proxy-public:
    external: true
